version: '3.7'
services:
    postgresql:
      image: postgres:latest
      restart: always
      shm_size: 128mb
      ports:
        - "5432:5432"
      env_file:
        - .env
      logging:
        options:
          max-size: 10m
          max-file: "3"
      networks:
        - movies_network

    movies-backend:
      restart: always
      depends_on:
        - postgresql
      env_file:
        - .env
      networks:
        - movies_network

networks:
    movies_network:
      external: true